### ISSUE TITLE
Requests are not answered on Ubuntu 18.04

### ISSUE THREAD

**Issue by mm-fee** [Singulink/Singulink.Net.Dhcp#1]
I took the example code and compiled it using .NET 5 and tried to run it on a Ubuntu 18.04 Server. No DHCP requests coming from another device were detected by the library. 

I tested the exact same setup with a different DHCP library and it worked - so no firewall or other network issue.

**Comment by mikernet** [comment]
Oh no, I'm not sure why I didn't get the notification for this issue - just checked my email and for some reason I never got one, so sorry about that! Just randomly stumbed upon this now.

It's probably too late but I would start by putting a breakpoint in `OnMessageError`, `OnSocketError` and `OnDiscoverReceived` and then step through.

**Comment by mikernet** [comment]
I believe this has been fixed by https://github.com/Singulink/Singulink.Net.Dhcp/pull/2 so I will close this issue for now.
